Merge config of build-aur-packages into main

diff --git a/.github/workflows/makepkg.yaml b/.github/workflows/makepkg.yaml
--- a/.github/workflows/makepkg.yaml
+++ b/.github/workflows/makepkg.yaml
@@ -173,3 +173,51 @@ jobs:
     - name: Deploy to GitHub Pages
       id: deploy
       uses: actions/deploy-pages@v4
+
+  test_simplebuild:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v6
+      with:
+        fetch-depth: 0
+        path: "src"
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v3
+      with:
+        platforms: "arm64"
+    - name: Build Packages amd64
+      uses: ./src/.github/actions/build-aur-packages
+      with:
+        packages: >
+          go-do
+          ttf-monocode
+    - name: Build Packages arm64
+      uses: ./src/.github/actions/build-aur-packages
+      with:
+        arch: "arm64"
+        arch-override: true
+        packages: >
+          go-do
+          ttf-monocode
+    - name: List and verify generated Files
+      run: |
+        find . -ls | tee ${{ github.workspace }}/files.txt
+        RC=0
+        for s in \
+          "go-do-*-x86_64.pkg.tar*" \
+          "ttf-monocode-*-any.pkg.tar*" \
+          "go-do-*-aarch64.pkg.tar*" \
+          ;
+        do
+          for f in $s ; do
+            if [ ! -f "$f" ] ; then
+              echo "$s not found"
+              RC=1
+            else
+              break
+            fi
+          done
+        done
+
+        exit $RC
